# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_configurable}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philipp Ullmann"]
  s.date = %q{2010-10-15}
  s.description = %q{Storage of configuration values in database}
  s.email = %q{philipp.ullmann@create.at}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "acts_as_configurable.gemspec",
     "lib/acts_as_configurable.rb",
     "lib/dummy_access.rb",
     "spec/acts_as_configurable_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/create-philipp-ullmann/acts_as_configurable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Storage of configuration values in database}
  s.test_files = [
    "spec/acts_as_configurable_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.3.1"])
      s.add_development_dependency(%q<activerecord>, [">= 3.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.3.1"])
      s.add_dependency(%q<activerecord>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.3.1"])
    s.add_dependency(%q<activerecord>, [">= 3.0.0"])
  end
end

